// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Ubn8v2QQxpV4ZzcPakp0rfDRbVoN57o',
    appId: '1:775366439566:web:b19ae72b988e16c2cf8fdf',
    messagingSenderId: '775366439566',
    projectId: 'tpmod12-872e9',
    authDomain: 'tpmod12-872e9.firebaseapp.com',
    storageBucket: 'tpmod12-872e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDVjYBnac_TPkG487Ql4sF5ULg3zT1Hfk',
    appId: '1:775366439566:android:8e278d84fe222f03cf8fdf',
    messagingSenderId: '775366439566',
    projectId: 'tpmod12-872e9',
    storageBucket: 'tpmod12-872e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx-O4X98iCLizcAK_aQ9qzQs9bNkLVju4',
    appId: '1:775366439566:ios:7857a01faf30437ecf8fdf',
    messagingSenderId: '775366439566',
    projectId: 'tpmod12-872e9',
    storageBucket: 'tpmod12-872e9.firebasestorage.app',
    iosBundleId: 'com.example.tpFlutterMod12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx-O4X98iCLizcAK_aQ9qzQs9bNkLVju4',
    appId: '1:775366439566:ios:7857a01faf30437ecf8fdf',
    messagingSenderId: '775366439566',
    projectId: 'tpmod12-872e9',
    storageBucket: 'tpmod12-872e9.firebasestorage.app',
    iosBundleId: 'com.example.tpFlutterMod12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0Ubn8v2QQxpV4ZzcPakp0rfDRbVoN57o',
    appId: '1:775366439566:web:e8e86b869e1bf9a3cf8fdf',
    messagingSenderId: '775366439566',
    projectId: 'tpmod12-872e9',
    authDomain: 'tpmod12-872e9.firebaseapp.com',
    storageBucket: 'tpmod12-872e9.firebasestorage.app',
  );
}
